train:
  _target_: src.datasets.VocoderDataset
  part: "train"
  instance_transforms: ${transforms.instance_transforms.train}
  sample_length: 25600 #256 * 100
val:
  _target_: src.datasets.VocoderDataset
  part: "val"
  instance_transforms: ${transforms.instance_transforms.inference}
  sample_length: 25600
  #limit: 16
