generator:
  _target_: src.model.Generator
  hidden_channels: 128
  upsample_iters: 4
  upsample_kernels: [16, 16, 4, 4]
  MRF_params:
    kernel_size: [3, 7, 11]
    dilations: [[[1,1], [3,1], [5,1]], [[1,1], [3,1], [5,1]], [[1,1], [3,1], [5,1]]]

MPD_dicriminator:
  _target_: src.model.MultiPeriodDiscriminator

MSD_dicriminator:
  _target_: src.model.MultiScaleDiscriminator
